cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path(
        'add/',
        views.cart_add_or_update,
        name='add_to_cart'
    ),
    path(
        'remove/',
        views.cart_remove,
        name='remove_from_cart'
    ),
    path(
        '',
        views.cart_detail,
        name='cart_detail'
    ),
]

eshop_sample_project/users/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path(
        'update-user-data/',
        views.update_user_data,
        name='update_user_data'
    ),
    path(
        'favorites/',
        views.favorites,
        name='favorites'
    ),
    path(
        'purchase_history/',
        views.purchase_history,
        name='purchase_history'
    ),
    path(
        'signup/',
        views.signup_view,
        name='signup'
    ),
    path(
        'login/',
        views.login_view,
        name='login'
    ),
    path(
        'logout/',
        views.user_logout,
        name='logout'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]

payment/urls.py
from django.urls import path

from payment import views

app_name = 'payment'

urlpatterns = [
    path('check-payment-status/', views.check_payment_status, name='check_payment_status'),
    path('process/', views.payment_process, name='process'),
    path('', views.payment_detail, name='detail')
]

eshop_sample_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from main.models import Product


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password,**extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
           raise ValueError(
               "Superuser must have is_staff=True."
           )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
               "Superuser must have is_superuser=True."
           )
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    email = models.EmailField(_('Email Address'), unique=True)
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()
    favourites = models.ManyToManyField(
        Product, 
        related_name='users', 
        verbose_name='Избранные товары'
    )
    # First Name and Last Name do not cover name patterns around the globe.

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

payment/models.py
from django.db import models

# Create your models here.

eshop_sample_project/users/views.py
import logging

from django.shortcuts import redirect, render
from django.db.models import F, FloatField, Sum, Prefetch, ObjectDoesNotExist
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseBadRequest

from . import forms
from main.utils import check_recaptcha, ajax_required, get_form_errors, query_debugger
from main.models import Product
from order.models import Order, OrderItem

logger = logging.getLogger(__name__)
logger.setLevel('INFO')

formatter = logging.Formatter('%(levelname)s:%(asctime)s:%(name)s:%(message)s')

file_handler = logging.FileHandler('logs/account_info.log')
file_handler.setLevel('INFO')
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

@check_recaptcha
def signup_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.UserCreationForm(data=request.POST, request=request)
        
        if form.is_valid():
            form.save()
            form.signup_success()
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/signup.html', context_data)


@check_recaptcha
def login_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.AuthenticationForm(data=request.POST, request=request)

        if form.is_valid():

            try:
                cart = request.session[settings.CART_SESSION_ID]
            except KeyError:
                cart = None
            
            try:
                order = request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                order = None

            form.authentication_success()

            try:
                request.session[settings.CART_SESSION_ID]
            except KeyError:
                if cart:
                    request.session[settings.CART_SESSION_ID] = cart
            
            try:
                request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                if order:
                    request.session[settings.ORDER_SESSION_ID] = order
                
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/login.html', context_data)

def user_logout(request):
    successful_url = request.GET.get('next', '/')

    try:
        cart = request.session[settings.CART_SESSION_ID]
    except KeyError:
        cart = None
    
    try:
        order = request.session[settings.ORDER_SESSION_ID]
    except KeyError:
        order = None
    
    logout(request)

    if cart:
        request.session[settings.CART_SESSION_ID] = cart
    
    if order:
        request.session[settings.ORDER_SESSION_ID] = order
    
    return redirect(successful_url)

class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'account/password_reset_form.html'
    email_template_name = 'account/password_reset_email.html'
    success_url = reverse_lazy('account:password_reset_done')
    from_email = settings.PROJECT_EMAIL_ADDRESS

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'account/password_reset_confirm.html'
    success_url = reverse_lazy('account:password_reset_complete')

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'account/password_reset_complete.html'

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'account/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        context['first_name'] = user.first_name
        context['last_name'] = user.last_name
        context['phone_number'] = user.phone_number
        context['email'] = user.email
            
        return context

@login_required
def purchase_history(request):
    user = request.user

    orderItem_querySet = OrderItem.objects                                                             \
        .select_related('product')                                                                     \
        .only('price', 'quantity', 'order_id', 'product_id', 'product__image', 'product__name',)       \
        .order_by('-quantity')
        
    order_list = Order.objects.filter(user=user)                                                       \
        .annotate(total_cost=Sum(F('items__quantity') * F('items__price'), output_field=FloatField())) \
        .only('payment_status', 'created')                                                             \
        .prefetch_related(Prefetch('items', queryset=orderItem_querySet))                              \
        .order_by('-created')

    return render(request, 'account/profile_orders_history.html', {'order_list': order_list})
        
    
@login_required
def favorites(request):

    if request.method == 'GET':
        user = request.user
        queryset = user.favourites.only('price', 'name', 'image')

        return render(request, 'account/profile_favorite.html', {'favourite_list': queryset})
    
    elif request.method == 'POST':
        action = request.POST.get('action')
        product_id = request.POST.get('product_id')

        error_list = []
        form = forms.ValidateFavouriteProducts(request=request, data=request.POST)

        if form.is_valid():
            if action == 'add-product':
                form.add_product() 
            elif action == 'remove-product':
                form.remove_product()
        else:
            error_list = get_form_errors(form)
        
        return JsonResponse({'errors': error_list})

    else:
        return HttpResponseBadRequest()


@ajax_required
def update_user_data(request):
    error_list = []

    if request.method == 'POST':
        form = forms.UpdateUserData(data=request.POST, request=request)

        if form.is_valid():
            form.update_data()

            return JsonResponse({'status': 'ok'})
        else:
            error_list = get_form_errors(form=form)
    
    return JsonResponse({'status': 'ko', 'errors': error_list})

payment/views.py
import uuid

from yandex_checkout import Payment, Refund

from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import ObjectDoesNotExist
from django.urls import reverse
from django.conf import settings

from order.models import Order
from payment.tasks import check_order_status
from cart.cart import Cart
from page.models import PaymentPage

def payment_detail(request):
    
    qs = PaymentPage.objects.all()

    if qs.exists():
        page = qs.first()
    else:
        page = PaymentPage.objects.create(name='Информация об оплате', title='Информация об оплате')

    context = {
        'page': page
    }
    context = {
        'page': 'page'
    }

    return render(request, 'payment/detail.html', context)

def payment_process(request):

    if not request.order:
        return redirect(reverse('order:new_order'))
    
    order = request.order
    payment = Payment.create({
        "amount": {
            "value": str(order.get_total_cost()),
            "currency": "RUB"
        },
        "confirmation": {
            "type": "redirect",
            "return_url": request.build_absolute_uri(reverse('payment:check_payment_status'))
        },
        "capture": True,
        "description": "Заказ №1"
    }, uuid.uuid4())

    order.payment_id = payment.id
    order.save()
    
    # check_order_status.apply_async((order.payment_id, order.id))
    return redirect(payment.confirmation.confirmation_url)

def check_payment_status(request):

    if not request.order:
        return redirect(reverse('order:new_order'))

    cart = Cart(request)
    order = request.order
    payment_id = order.payment_id

    payment = Payment.find_one(payment_id)

    if payment.status == 'succeeded':
        order.payment_status = 'succeeded'

        for orderLine in order.items.all():
            product = orderLine.product
            quantity = orderLine.quantity

            product.number_reserved -= quantity
            product.number_purchased += quantity
            product.save()
        
        order.save()
        cart.clear()
        del request.session['order']

        return redirect(reverse('order:done', kwargs={'order_id': order.id}))
    
    elif payment.status == 'canceled':
        order.payment_status = 'canceled'

        for orderLine in order.items.all():
            product = orderLine.product
            quantity = orderLine.quantity

            product.number_reserved -= quantity
            product.number_in_stock += quantity
            product.save()
        
        order.save()

        return redirect(reverse('order:canceled', kwargs={'order_id': order.id}))
    
    elif payment.status == 'waiting_for_capture':
        order.payment_status = 'waiting_for_capture'

        for orderLine in order.items.all():
            product = orderLine.product
            quantity = orderLine.quantity

            product.number_reserved -= quantity
            product.number_purchased += quantity
            product.save()
        
        order.save()
        cart.clear()
        del request.session['order']

        return redirect(reverse('order:done', kwargs={'order_id': order.id}))
    
    elif payment.status == 'pending':
       return redirect(reverse('order:new_order'))

    else:
        return redirect(reverse('order:canceled', kwargs={'order_id': order.id}))

def payment_refund(order_id, amount):
    response = {}
    error_list = []

    try:
        order = Order.objects.get(id=order_id)
        payment_id = order.payment_id

        payment = Payment.find_one(payment_id)

        if payment.status == 'succeeded':
            refund = Refund.create({
                "amount": {
                    "value": amount,
                    "currency": "RUB"
                },
                "payment_id": payment_id
            })

            if refund.status == 'succeeded':
                return 'Ok'
            else:
                error_list.append(
                    'Refund was not successful.'
                )
    except ObjectDoesNotExist:
        error_list.append(
            'Order does not exist.'
        )
    except AttributeError:
        error_list.append(
            'Order does not have payment_id attribute.'
        )
    return error_list

eshop_sample_project/templates/payment/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ page.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/payment_detail-style.css' %}">
{% endblock css %}

{% block content %}

<div id="main-container-about">

    <!-- breadcrumbs -->
    <ul id="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item active"><a href="#">{{ page.name }}</a></li>
    </ul>

    {% comment %} <h3>Оплата</h3> {% endcomment %}
    <div class="main-info">
        {{ page.stream.render }}
    </div>

</div>

{% endblock content %}

eshop_sample_project/templates/payment/process.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Кодировка веб-страницы -->
    <meta charset="utf-8">
    <!-- Настройка viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Настройка title -->
    <title>Оплата</title>

    <!-- Подключаем Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Подключаем FontAwesome -->
    <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">

    <!-- Шрифты -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

    <!-- base css -->
    <link rel="stylesheet" href="{% static 'css/payment_process-style.css' %}">

</head>

<body>

    <div class="container container-table">
        <div class="row vertical-center-row">
            <div id="pseudo-modal" class="col">
                <div class="container">

                    <h5>Оплачивайте безопасно с помощью вашей карты</h5>

                    <hr>


                    <form id='payment_form' action="{% url 'payment:process' %}" method='POST' class="needs-validation"
                        novalidate="">
                        <div class="inputs-block">
                            <!-- номер карты -->
                            <div class="form-group justify-content-center align-items-center">
                                <label for="cc-number">Номер карты</label>
                                <div class="form-control pseudo-input" id="cc-number"></div>
                                <div class="invalid-feedback">
                                    Credit card number is required
                                </div>
                            </div>

                            <div class="form-row mt-3">

                                <!-- срок действия -->
                                <div class="form-group col">
                                    <label for="cc-expiration">Срок действия<span
                                            class="span-in-label">(ММ/ГГ)</span></label>
                                    <div class="form-control pseudo-input" id="cc-expiration"></div>
                                    <div class="invalid-feedback">
                                        Expiration date required
                                    </div>
                                </div>

                                <!-- код безопасности -->
                                <div class="form-group col">
                                    <label for="cc-cvv">Код безопасности<span class="span-in-label">(3
                                            цифры)</span></label>
                                    <div class="form-control pseudo-input" id="cc-cvv"></div>
                                    <div class="invalid-feedback">
                                        Security code required
                                    </div>
                                </div>
                            </div>
                        </div>

                        {% csrf_token %}

                        <!-- кнопка оплаты -->
                        <div class="text-center">
                            <button class="pay-button btn btn-primary btn-lg" type="submit">Оплатить</button>
                        </div>
                    </form>


                    <!-- заметка для оплаты -->
                    <div class="notes-for-pay">
                        Нажимая "Оплатить" Вы соглашаетесь с нашей <a href="#">Политикой возврата средств</a>
                    </div>

                    <hr>

                    <!-- заметка о конфиденциальности -->
                    <div class="privacy-info">
                        Все данные платежей надежно шифруются и обрабатываются платежной системой Braintree (сервис
                        PayPal).
                        Мы не храним и не собираем конфиденциальные данные платежей на наших серверах.
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap inspired Braintree Hosted Fields example -->
    <!-- <div class="bootstrap-basic">
        <form id='payment_form' action='{% url 'payment:process' %}' method='POST' class="needs-validation" novalidate="">
    
        <div class="row">
            <div class="col-sm-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required="true">
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">
                Name on card is required
            </div>
            </div>
            <div class="col-sm-6 mb-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="you@example.com">
            <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
            </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-sm-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <div class="form-control" id="cc-number"></div>
            <div class="invalid-feedback">
                Credit card number is required
            </div>
            </div>
            <div class="col-sm-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <div class="form-control" id="cc-expiration"></div>
            <div class="invalid-feedback">
                Expiration date required
            </div>
            </div>
            <div class="col-sm-3 mb-3">
            <label for="cc-expiration">CVV</label>
            <div class="form-control" id="cc-cvv"></div>
            <div class="invalid-feedback">
                Security code required
            </div>
            </div>
        </div>

        {% csrf_token %}
    
        <hr class="mb-4">
        <div class="text-center">
        <button class="btn btn-primary btn-lg" type="submit">Pay with <span id="card-brand">Card</span></button>
        </div>

        </form>
    </div>
    <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
        <div class="toast-header">
        <strong class="mr-auto">Success!</strong>
        <small>Just now</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="toast-body">
        Next, submit the payment method nonce to your server.
        </div>
    </div>
    </div> -->




    <!-- Подключаем jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Подключаем плагин Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

    <!-- Подключаем Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <!-- Load the required client component. -->
    <script src="https://js.braintreegateway.com/web/3.60.0/js/client.min.js"></script>

    <!-- Load Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.60.0/js/hosted-fields.min.js"></script>

    <script>
        var form = $('#payment_form');

        braintree.client.create({
            authorization: '{{ client_token }}'
        }, function (err, clientInstance) {
            if (err) {
                console.error(err);
                return;
            }

            braintree.hostedFields.create({
                client: clientInstance,
                styles: {
                    input: {
                        // change input styles to match
                        // bootstrap styles
                        'font-size': '1rem',
                        color: '#495057'
                    }
                },
                fields: {
                    number: {
                        selector: '#cc-number',
                        placeholder: '4111 1111 1111 1111'
                    },
                    cvv: {
                        selector: '#cc-cvv',
                        placeholder: '123'
                    },
                    expirationDate: {
                        selector: '#cc-expiration',
                        placeholder: 'MM / YY'
                    }
                }
            }, function (err, hostedFieldsInstance) {
                if (err) {
                    console.error(err);
                    return;
                }

                form.submit(function (event) {

                    var formIsInvalid = false;
                    var state = hostedFieldsInstance.getState();

                    hostedFieldsInstance.tokenize({
                        // include the cardholderName in the tokenization
                        // request
                        cardholderName: $('#cc-name').val()
                    }, function (err, payload) {
                        if (err) {
                            console.error(err);
                            return;
                        }

                        // This is where you would submit payload.nonce to your server
                        $('.toast').toast('show');

                        // you can either send the form values with the payment
                        // method nonce via an ajax request to your server,
                        // or add the payment method nonce to a hidden inpiut
                        // on your form and submit the form programatically
                        $('#payment-method-nonce').val(payload.nonce);
                        form.submit()
                    });
                });
            });
        });
    </script>
</body>

</html>