cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path(
        'add/',
        views.cart_add_or_update,
        name='add_to_cart'
    ),
    path(
        'remove/',
        views.cart_remove,
        name='remove_from_cart'
    ),
    path(
        '',
        views.cart_detail,
        name='cart_detail'
    ),
]

eshop_sample_project/users/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path(
        'update-user-data/',
        views.update_user_data,
        name='update_user_data'
    ),
    path(
        'favorites/',
        views.favorites,
        name='favorites'
    ),
    path(
        'purchase_history/',
        views.purchase_history,
        name='purchase_history'
    ),
    path(
        'signup/',
        views.signup_view,
        name='signup'
    ),
    path(
        'login/',
        views.login_view,
        name='login'
    ),
    path(
        'logout/',
        views.user_logout,
        name='logout'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        '500/', 
        views.error500, 
        name = '500'
    ),
    path(
        '404/', 
        views.error404, 
        name = '404'
    ),
    path(
        'search/', 
        views.search, 
        name = 'search'
    ),
    path(
        'product-list-by-filter/', 
        views.product_list_by_filter, 
        name = 'product_list_by_filter'
    ),
    path(
        'ajax/get-filter-data/', 
        views.getFilterData, 
        name='get_filter_data'
    ),
    path(
        'set-user-city/',
        views.save_user_city_in_session,
        name='set_user_city'
    ),
    path(
        'products/',
        views.product_list_view,
        name='product_list'
    ),
    path(
        'products/<slug:category_slug>/',
        views.product_list_view,
        name='product_list_by_category'
    ),
    path(
        'product/<uuid:pk>/<slug:slug>/', 
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    path(
        'otzywy/',
        views.RepliesPageView.as_view(),
        name='replies'
    ),
    path(
        'shipping/',
        views.ShippingPageView.as_view(),
        name='shipping'
    ),
    path(
        'contact-us/',
        views.ContactUsPageView.as_view(),
        name='contact_us'
    ),
    path(
        'about-us/',
        views.AboutUsPageView.as_view(),
        name='about_us'
    ),
    path(
        '',
        views.home_page_view,
        name='home'
    ),
]

main/forms.py
import logging

from django import forms
from django.db import models
from django.core.mail import send_mail
from django.conf import settings

from main.models import ProductFeature, CategoryFeature

logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    email= forms.EmailField(required=False)
    message = forms.CharField(required=False)

    error_messages = {
        'email_missed': 'Вы не указали email для обратной связи.',
        'message_missed': 'Вы ничего не написали в своём сообщении.'
    }

    def clean(self):
        email = self.cleaned_data.get('email', None)
        message = self.cleaned_data.get('message', None)

        if not email:
            raise forms.ValidationError(
                self.error_messages['email_missed'],
                code='email_missed'
            )

        if not message:
            raise forms.ValidationError(
                self.error_messages['message_missed'],
                code='message_missed'
            )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "От: {0}\n{1}".format(
            self.cleaned_data["email"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Кто-то захотел связаться с Вами.",
            message,
            settings.PROJECT_EMAIL_ADDRESS,
            [settings.PROJECT_CUSTOMER_SERVICE_EMAIL_ADDRESS],
            fail_silently=False,
        )

class SetUserCityForm(forms.Form):
    status = forms.CharField(required=False)
    city = forms.CharField(required=False)

    error_messages = {
        'status_missed': 'Status is not found.',
        'city_missed': 'User city is not found.',
        'already_set': 'City has been already set.'
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        status = self.cleaned_data.get('status')
        city = self.cleaned_data.get('city')

        if not status:
            raise forms.ValidationError(
                self.error_messages['status_missed'],
                code='status_missed',
            )
        if not city:
            raise forms.ValidationError(
                self.error_messages['city_missed'],
                code='city_missed',
            )
        if self.request:
            current_city = self.request.session.get(settings.CITY_SESSION_ID)
            if current_city:
                raise forms.ValidationError(
                    self.error_messages['already_set'],
                    code='already_set',
                )

    def set_new_city(self):
        session = self.request.session
        city = self.cleaned_data.get('city')
        
        session[settings.CITY_SESSION_ID] = city

class ProductFeatureCreationForm(forms.ModelForm):
    class Meta:
        model = ProductFeature
        fields = ['product', 'header', 'name', 'value', 'active']
    
    error_messages = {
        'feature_already_exists': 'Выбранный товар уже имеет идиентичную характеристику',
        'product_field_not_found': {
            'product': ['Обязательное поле']
        },
        'header_field_not_found': {
            'header': ['Обязательное поле']
        },
        'name_field_not_found': {
            'name': ['Обязательное поле']
        },
    }

    def clean(self):
        product = self.cleaned_data.get('product')
        header = self.cleaned_data.get('header')
        name = self.cleaned_data.get('name')

        if not product:
            raise forms.ValidationError(
                self.error_messages['product_field_not_found'],
                code='product_field_not_found',
            )
        if not header:
            raise forms.ValidationError(
                self.error_messages['header_field_not_found'],
                code='header_field_not_found',
            )
        if not name:
            raise forms.ValidationError(
                self.error_messages['name_field_not_found'],
                code='name_field_not_found',
            )
        # Проверяем, что выбранный товар не имеет идиентичной характеристики.
        try:
            feature = ProductFeature.objects.get(product=product, header=header.capitalize(), name=name.capitalize())
            if feature.id != self.instance.id:
                raise forms.ValidationError(
                    self.error_messages['feature_already_exists'],
                    code='feature_already_exists',
                )
        except models.ObjectDoesNotExist:
            pass

class CategoryFeatureCreationForm(forms.ModelForm):
    class Meta:
        model = CategoryFeature
        fields = ['category', 'header', 'name', 'value', 'activate_feature', 'activate_filter']
    
    error_messages = {
        'feature_already_exists': 'Выбранная категория уже имеет идиентичную характеристику',
        'category_field_not_found': {
            'category': ['Обязательное поле']
        },
        'header_field_not_found': {
            'header': ['Обязательное поле']
        },
        'name_field_not_found': {
            'name': ['Обязательное поле']
        },
    }

    def clean(self):
        category = self.cleaned_data.get('category')
        header = self.cleaned_data.get('header')
        name = self.cleaned_data.get('name')

        if not category:
            raise forms.ValidationError(
                self.error_messages['category_field_not_found'],
                code='category_field_not_found',
            )
        if not header:
            raise forms.ValidationError(
                self.error_messages['header_field_not_found'],
                code='header_field_not_found',
            )
        if not name:
            raise forms.ValidationError(
                self.error_messages['name_field_not_found'],
                code='name_field_not_found',
            )
        
        # Проверяем, что выбранныая категория не имеет идиентичной характеристики.
        try:
            feature = CategoryFeature.objects.get(category=category, header=header.capitalize(), name=name.capitalize())
            if feature.id != self.instance.id:
                raise forms.ValidationError(
                    self.error_messages['feature_already_exists'],
                    code='feature_already_exists',
                )
        except models.ObjectDoesNotExist:
            pass

eshop_sample_project/users/views.py
import logging

from django.shortcuts import redirect, render
from django.db.models import F, FloatField, Sum, Prefetch, ObjectDoesNotExist
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseBadRequest

from . import forms
from main.utils import check_recaptcha, ajax_required, get_form_errors, query_debugger
from main.models import Product
from order.models import Order, OrderItem

logger = logging.getLogger(__name__)
logger.setLevel('INFO')

formatter = logging.Formatter('%(levelname)s:%(asctime)s:%(name)s:%(message)s')

file_handler = logging.FileHandler('logs/account_info.log')
file_handler.setLevel('INFO')
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

@check_recaptcha
def signup_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.UserCreationForm(data=request.POST, request=request)
        
        if form.is_valid():
            form.save()
            form.signup_success()
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/signup.html', context_data)


@check_recaptcha
def login_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.AuthenticationForm(data=request.POST, request=request)

        if form.is_valid():

            try:
                cart = request.session[settings.CART_SESSION_ID]
            except KeyError:
                cart = None
            
            try:
                order = request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                order = None

            form.authentication_success()

            try:
                request.session[settings.CART_SESSION_ID]
            except KeyError:
                if cart:
                    request.session[settings.CART_SESSION_ID] = cart
            
            try:
                request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                if order:
                    request.session[settings.ORDER_SESSION_ID] = order
                
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/login.html', context_data)

def user_logout(request):
    successful_url = request.GET.get('next', '/')

    try:
        cart = request.session[settings.CART_SESSION_ID]
    except KeyError:
        cart = None
    
    try:
        order = request.session[settings.ORDER_SESSION_ID]
    except KeyError:
        order = None
    
    logout(request)

    if cart:
        request.session[settings.CART_SESSION_ID] = cart
    
    if order:
        request.session[settings.ORDER_SESSION_ID] = order
    
    return redirect(successful_url)

class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'account/password_reset_form.html'
    email_template_name = 'account/password_reset_email.html'
    success_url = reverse_lazy('account:password_reset_done')
    from_email = settings.PROJECT_EMAIL_ADDRESS

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'account/password_reset_confirm.html'
    success_url = reverse_lazy('account:password_reset_complete')

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'account/password_reset_complete.html'

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'account/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        context['first_name'] = user.first_name
        context['last_name'] = user.last_name
        context['phone_number'] = user.phone_number
        context['email'] = user.email
            
        return context

@login_required
def purchase_history(request):
    user = request.user

    orderItem_querySet = OrderItem.objects                                                             \
        .select_related('product')                                                                     \
        .only('price', 'quantity', 'order_id', 'product_id', 'product__image', 'product__name',)       \
        .order_by('-quantity')
        
    order_list = Order.objects.filter(user=user)                                                       \
        .annotate(total_cost=Sum(F('items__quantity') * F('items__price'), output_field=FloatField())) \
        .only('payment_status', 'created')                                                             \
        .prefetch_related(Prefetch('items', queryset=orderItem_querySet))                              \
        .order_by('-created')

    return render(request, 'account/profile_orders_history.html', {'order_list': order_list})
        
    
@login_required
def favorites(request):

    if request.method == 'GET':
        user = request.user
        queryset = user.favourites.only('price', 'name', 'image')

        return render(request, 'account/profile_favorite.html', {'favourite_list': queryset})
    
    elif request.method == 'POST':
        action = request.POST.get('action')
        product_id = request.POST.get('product_id')

        error_list = []
        form = forms.ValidateFavouriteProducts(request=request, data=request.POST)

        if form.is_valid():
            if action == 'add-product':
                form.add_product() 
            elif action == 'remove-product':
                form.remove_product()
        else:
            error_list = get_form_errors(form)
        
        return JsonResponse({'errors': error_list})

    else:
        return HttpResponseBadRequest()


@ajax_required
def update_user_data(request):
    error_list = []

    if request.method == 'POST':
        form = forms.UpdateUserData(data=request.POST, request=request)

        if form.is_valid():
            form.update_data()

            return JsonResponse({'status': 'ok'})
        else:
            error_list = get_form_errors(form=form)
    
    return JsonResponse({'status': 'ko', 'errors': error_list})

eshop_sample_project/templates/main/about_us.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ page.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/about_us-style.css' %}">
{% endblock css %}

{% block content %}

<div id="main-container-about">

  <!-- breadcrumbs -->
  <ul id="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
    <li class="breadcrumb-item active"><a href="#">{{ page.name }}</a></li>
  </ul>

  {{ page.stream.render }}

  <div class="container-fluid mt-5">
    <div class="map-about">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d577336.7627686693!2d36.82514723492826!3d55.58074815884876!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b54afc73d4b0c9%3A0x3d44d6cc5757cf4c!2z0JzQvtGB0LrQstCw!5e0!3m2!1sru!2sru!4v1581409081538!5m2!1sru!2sru"
        width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>

  </div>
</div>





{% endblock content %}

eshop_sample_project/templates/main/contact_us.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ page.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/contact_us-style.css' %}">
{% endblock css %}

{% block content %}

<div id="main-container-about">

  <!-- breadcrumbs -->
  <ul id="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
    <li class="breadcrumb-item active"><a href="#">{{ page.name }}</a></li>
  </ul>

  {% comment %} <h3>Контакты</h3> {% endcomment %}
  <div class="main-info">
    {{ page.stream.render }}
  </div>

</div>

{% endblock content %}

eshop_sample_project/templates/main/home.html
{% extends "base.html" %} {% load static %} {% block title %}{{ page.title }}{% endblock title %} {% block css %}
<link rel="stylesheet" href="{% static 'css/home-style.css' %}"> {% endblock css %} {% block content %}
<div id="main-container-home">
    <div class="row">
        {{ page.stream.render }}
    </div>
</div>

<!-- advantages -->
<!-- <div id="advantages-area">
  <div class="container">
    <div class="row text-center align-items-center">
      <div class="col-md-3 col-6"><i class="fas fa-book-open"></i><br>Большой выбор товаров</div>
      <div class="col-md-3 col-6"><i class="fas fa-truck"></i><br>Единый тариф на доставку</div>
      <div class="col-md-3 col-6"><i class="fas fa-hand-holding-usd"></i><br>Гарантии производителя</div>
      <div class="col-md-3 col-6"><i class="fas fa-headphones"></i><br>Бесплатное консультирование</div>
    </div>
  </div>
</div> -->

{% endblock content %}

eshop_sample_project/templates/main/product_detail.html
{% extends 'base.html' %} {% load static %} {% block title %}{{ product.name }}{% endblock title %} {% block css %}
<link rel="stylesheet" href="{% static 'css/product_detail-style.css' %}"> {% endblock css %} {% block content %}

<!-- main content -->
<div id="main-container-product">

    <!-- breadcrumbs -->
    <ul id="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{% url 'product_list' %}">Все товары</a></li>
        <li class="breadcrumb-item active"><a href="#">Унитазы</a></li>
    </ul>

    <!-- caption of the product -->
    <h4 id="caption-product" data-id="{{ product.id }}">{{ product.name }}</h4>

    <!-- main row -->
    <div class="row-for-picture-and-details">
        <!-- main picture -->
        <div class="picture-area">
            <div id="carousel-picture" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="picture-of-the-product">
                            <div class="wrapper-for-the-picture">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}">
                                {% else %}
                                    <img src="{{ product.get_default_image_url }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% for image_obj in product.extra_images.all %}
                        <div class="carousel-item">
                            <div class="picture-of-the-product">
                                <div class="wrapper-for-the-picture">
                                    <img src="{{ image_obj.image.url }}">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
                </div>
                <a class="carousel-control-prev" href="#carousel-picture" role="button" data-slide="prev">
                    <ion-icon name="chevron-back-outline" class="new-icon-control"></ion-icon>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel-picture" role="button" data-slide="next">
                    <ion-icon name="chevron-forward-outline" class="new-icon-control"></ion-icon>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="details-area">

            <div class="details-info-area">
                <div>Доступность:<span class="available-status">В наличии</span><span class="unvaliable-status">Нет в
                        наличии</span></div>
                <div>Самовывоз:<span class="colorful-span">Отсутствует</span></div>
                <div>До двери:<span class="colorful-span">300 р.</span></div>
                <div>До пункта ПВЗ:<span class="colorful-span">150 р.</span></div>
                <div>Гарантия:<span class="colorful-span">12 месяцев</span></div>
                <div>Артикул:<span class="colorful-span">123456789</span></div>
                <div>Бренд:<span class="colorful-span">Swahhh</span></div>
                <div>Коллекция:<span class="colorful-span">Хельсинки</span></div>
                <div>Страна:<span class="colorful-span">Россия</span></div>
                <div>Коллекция:<span class="colorful-span">Хельсинки</span></div>
                <div>Страна:<span class="colorful-span">Россия</span></div>
            </div>

            <div class="price-and-buttons-area">
                <div class="price-product">
                    16 999 p.
                </div>

                <div class="buttons-area">
                    <div class="first-buttons">
                        <a href="{% url 'cart:add_to_cart' %}?next={% url 'cart:cart_detail' %}" class="btn-instant-buy"><i class="far fa-heart"></i></a>
                        <a href="#" class="btn-compare"><i class="fas fa-balance-scale"></i>В сравнение</a>
                    </div>
                    <div class="second-buttons">
                        <a href="{% url 'cart:add_to_cart' %}" id='add_to_cart_link' type='submit' class="btn btn-warning btn-add-to-basket"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="picture-of-the-product">
                <div class="wrapper-for-the-picture">
                    <img id='product-picture-url' src="{{ product.get_public_image_url }}">
                </div>
                <div class="badge-for-img-product">
          АКЦИЯ
        </div>
            </div> -->

    <!-- small pictures -->
    <!-- <div class="pictures-of-the-product">
                {% for image_obj in product.images.all %}
                <div class="wrapper-for-small-pictures">
                    <img src="{{ image_obj.image.url }}">
                </div>
                {% endfor %}
            </div> -->


    <div class="row">
        <!-- all features -->
        <div class="col-md-12 col-xl-12">
            <ul class="nav nav-tabs" id="feature-and-desc" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="desc-tab" data-toggle="tab" href="#desc" role="tab" aria-controls="desc" aria-selected="true">Описание</a>
                </li>
                {% if product.features %}
                <li class="nav-item">
                    <a class="nav-link" id="feature-tab" data-toggle="tab" href="#feature" role="tab" aria-controls="feature" aria-selected="false">Характеристики</a>
                </li>
                {% endif %}
            </ul>
            <div class="tab-content" id="feature-and-desc-content">

                <div class="tab-pane fade show active" id="desc" role="tabpanel" aria-labelledby="desc-tab">
                    <div class="description-of-the-product">

                        <div class="desc-text">
                            {{ product.description|safe|default:'Описание отсутствует' }}
                        </div>

                    </div>
                </div>

                <div class="tab-pane fade" id="feature" role="tabpanel" aria-labelledby="feature-tab">
                    <div class="feature">
                        <h5 class="main-capture">Характеристики</h5>
                        <div class="row">
                            {% for feature in product.get_features %} {% ifchanged feature.header %} {% with feature.header as current_header %}
                            <div class="col-md-12 col-12">
                                <div class="features-area">
                                    <h6 class="capture-features">{{ current_header }}</h6>
                                    <div class="col-for-features-list">
                                        {% for feature in product.get_features %} {% if feature.header == current_header %}
                                        <div class="feature-item">
                                            <span class="feature-name">{{ feature.name }}</span>
                                            <span class="feature-dots"></span>
                                            <span class="feature-data">{{ feature.value }}</span>
                                        </div>
                                        {% endif %} {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% endwith %} {% endifchanged %} {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %} {% block js %}
<script src="{% static 'js/product_detail.js' %}"></script>
{% endblock js %}

eshop_sample_project/templates/main/replies.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ page.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/replies-style.css' %}">
{% endblock css %}

{% block content %}

<div id="main-container-about">

    <!-- breadcrumbs -->
    <ul id="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item active"><a href="#">{{ page.name }}</a></li>
    </ul>

    {% comment %} <h3>Отзывы</h3> {% endcomment %}
    <div class="main-info">
        {{ page.stream.render }}
    </div>
</div>

{% endblock content %}

eshop_sample_project/templates/main/search_results.html
<!-- templates/books/search_results.html -->
{% extends 'base.html' %}

{% block title %}Поиск по сайту{% endblock title %}
{% block content %}

<h1>Поиск по сайту: {{ user_query }}</h1>

    {% for product in search_result_list %}
        <div>
        <h3><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
        <p>Author: {{ product.brand }}</p>
        <p>Price: $ {{ product.price }}</p>
        </div>
    {% empty %}
        <h3>К сожалению, по вашему запросу ничего не найдено.</h3>
    {% endfor %}

{% endblock content %}

eshop_sample_project/templates/main/shipping.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ page.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/shipping-style.css' %}">
{% endblock css %}

{% block content %}

<div id="main-container-about">

  <!-- breadcrumbs -->
  <ul id="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
    <li class="breadcrumb-item active"><a href="#">{{ page.name }}</a></li>
  </ul>

  {% comment %} <h3>Доставка</h3> {% endcomment %}
  <div class="main-info">
      {{ page.stream.render }}
  </div>
</div>

{% endblock content %}