cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path(
        'add/',
        views.cart_add_or_update,
        name='add_to_cart'
    ),
    path(
        'remove/',
        views.cart_remove,
        name='remove_from_cart'
    ),
    path(
        '',
        views.cart_detail,
        name='cart_detail'
    ),
]

eshop_sample_project/users/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path(
        'update-user-data/',
        views.update_user_data,
        name='update_user_data'
    ),
    path(
        'favorites/',
        views.favorites,
        name='favorites'
    ),
    path(
        'purchase_history/',
        views.purchase_history,
        name='purchase_history'
    ),
    path(
        'signup/',
        views.signup_view,
        name='signup'
    ),
    path(
        'login/',
        views.login_view,
        name='login'
    ),
    path(
        'logout/',
        views.user_logout,
        name='logout'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]

order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path(
        '<int:order_id>/canceled/',
        views.order_canceled,
        name='canceled'
    ),
    path(
        '<int:order_id>/done/',
        views.order_done,
        name='done'
    ),
    path(
        'new-order/',
        views.new_order,
        name='new_order'
    ),
    path(
        'admin/order/<int:order_id>/',
        views.admin_order_detail,
        name='admin_order_detail'
    ),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.conf import settings

from main import models
from cart.cart import Cart

class CartAddProductForm(forms.Form):
    product_id= forms.UUIDField(required=False)
    quantity = forms.IntegerField(required=False)
    update = forms.BooleanField(required=False, initial=False)

    error_messages = {
        'product_id_missed': '"product_id" is not found or incorrect.',
        'product_does_not_exist': 'Product does not exist.',
        'quantity_missed': '"quantity" is not found.',
        'quantity_less_than_1': 'Quantity must not be less than 1.',
        'quantity_more_than_number_in_stock': 'Quantity must be less than product number in stock.'
    }

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        cart = self.request.session.get(settings.CART_SESSION_ID)

        product_id = self.cleaned_data.get('product_id')
        quantity = self.cleaned_data.get('quantity')
        update = self.cleaned_data.get('update')

        if not product_id:
            raise forms.ValidationError(
                self.error_messages['product_id_missed'],
                code='product_id_missed'
            )
        if not quantity:
            raise forms.ValidationError(
                self.error_messages['quantity_missed'],
                code='quantity_missed'
            )
        elif quantity < 1:
            raise forms.ValidationError(
                self.error_messages['quantity_less_than_1'],
                code='quantity_less_than_1'
            )
        if product_id:
            if not models.Product.objects.active().filter(id=product_id).exists():
                raise forms.ValidationError(
                    self.error_messages['product_does_not_exist'],
                    code='product_does_not_exist'
                )
            else:
                product = models.Product.objects.get(id=product_id)
        if cart:
            if str(product_id) in cart:
                product_quantity_in_cart = cart[str(product_id)]['quantity']
                if not update:
                    # Обычное повторное добавление товара в корзину без update quantity
                    if (product_quantity_in_cart + quantity) > product.number_in_stock:
                        raise forms.ValidationError(
                            'Max available product quantity is {}'.format(product.number_in_stock),
                            code='quantity_more_than_number_in_stock'
                        )
                else:
                    # Обычное обновление колличества товара в корзине. Т.е update = True
                    if quantity > product.number_in_stock:
                        raise forms.ValidationError(
                            'Max available product quantity is {}'.format(product.number_in_stock),
                            code='quantity_more_than_number_in_stock'
                        )
            # Абсолютно первое добавление товара в уже инициализированную корзину
            elif quantity > product.number_in_stock:
                raise forms.ValidationError(
                    'Max available product quantity is {}'.format(product.number_in_stock),
                    code='quantity_more_than_number_in_stock'
                )
        # Абсолютно первое добавление товара в ещё не инициализированную корзину
        elif quantity > product.number_in_stock:
            raise forms.ValidationError(
                'Max available product quantity is {}'.format(product.number_in_stock),
                code='quantity_more_than_number_in_stock'
            )

    def add_product_to_cart(self):
        product_id = self.cleaned_data.get('product_id')
        quantity = self.cleaned_data.get('quantity')
        update = self.cleaned_data.get('update')

        cart = Cart(self.request)
        product = models.Product.objects.get(id=product_id)

        cart.add(product=product,                 
            quantity=quantity,                 
            update_quantity=update
        )

class CartRemoveProductForm(forms.Form):
    product_id = forms.UUIDField(required=False)

    error_messages = {
        'product_id_missed': '"product_id" is not found or incorrect.',
        'product_does_not_exist': 'Product does not exist.',
        'cart_is_not_determined': 'Cart is not determined in the user session.',
        'product_is_not_in_cart': 'Product does not belong to the user cart.'
        
    }

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        cart = self.request.session.get(settings.CART_SESSION_ID)

        product_id = self.cleaned_data.get('product_id')

        if not product_id:
            raise forms.ValidationError(
                self.error_messages['product_id_missed'],
                code='product_id_missed'
            )
        elif not models.Product.objects.active().filter(id=product_id).exists():
                raise forms.ValidationError(
                    self.error_messages['product_does_not_exist'],
                    code='product_does_not_exist'
                )
        if not cart:
            raise forms.ValidationError(
                self.error_messages['cart_is_not_determined'],
                code='cart_is_not_determined'
            )
        elif str(product_id) not in cart:
                raise forms.ValidationError(
                    self.error_messages['product_is_not_in_cart'],
                    code='product_is_not_in_cart'
                )
    
    def remove_product_from_cart(self):
        product_id = self.cleaned_data.get('product_id')

        cart = Cart(self.request)    
        product = models.Product.objects.get(id=product_id)

        cart.remove(product)    
    

cart/views.py
from django.shortcuts import render
from django.http import JsonResponse

from main.utils import ajax_required, get_form_errors
from cart.cart import Cart
from cart import forms

@ajax_required
def cart_add_or_update(request):
    """Adding product to cart by one or updating quantity to certain number"""
    form = forms.CartAddProductForm(data=request.POST, request=request)
    
    if form.is_valid(): 
        form.add_product_to_cart()
        return JsonResponse({'status': 'ok'}, safe=False)
    else:  
        error_list = get_form_errors(form)
        return JsonResponse({'status': 'ko', 'errors': error_list}, safe=False)

@ajax_required
def cart_remove(request):  
    """Removing product from user cart"""
    form = forms.CartRemoveProductForm(data=request.POST, request=request)
    
    if form.is_valid(): 
        form.remove_product_from_cart()
        return JsonResponse({'status': 'ok'}, safe=False)
    else:  
        error = form.non_field_errors()[0]
        return JsonResponse({'status': 'ko', 'error': error}, safe=False)

def cart_detail(request):    
    cart = Cart(request)    
    return render(request, 'cart/cart.html', {'cart': cart}) 
    

eshop_sample_project/users/views.py
import logging

from django.shortcuts import redirect, render
from django.db.models import F, FloatField, Sum, Prefetch, ObjectDoesNotExist
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseBadRequest

from . import forms
from main.utils import check_recaptcha, ajax_required, get_form_errors, query_debugger
from main.models import Product
from order.models import Order, OrderItem

logger = logging.getLogger(__name__)
logger.setLevel('INFO')

formatter = logging.Formatter('%(levelname)s:%(asctime)s:%(name)s:%(message)s')

file_handler = logging.FileHandler('logs/account_info.log')
file_handler.setLevel('INFO')
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

@check_recaptcha
def signup_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.UserCreationForm(data=request.POST, request=request)
        
        if form.is_valid():
            form.save()
            form.signup_success()
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/signup.html', context_data)


@check_recaptcha
def login_view(request):
    successful_url = request.GET.get('next', '/')
    context_data = {
        'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY,
    }

    if request.method == 'POST':
        form = forms.AuthenticationForm(data=request.POST, request=request)

        if form.is_valid():

            try:
                cart = request.session[settings.CART_SESSION_ID]
            except KeyError:
                cart = None
            
            try:
                order = request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                order = None

            form.authentication_success()

            try:
                request.session[settings.CART_SESSION_ID]
            except KeyError:
                if cart:
                    request.session[settings.CART_SESSION_ID] = cart
            
            try:
                request.session[settings.ORDER_SESSION_ID]
            except KeyError:
                if order:
                    request.session[settings.ORDER_SESSION_ID] = order
                
            return redirect(successful_url)
        else:
            context_data['form'] = form

    return render(request, 'account/login.html', context_data)

def user_logout(request):
    successful_url = request.GET.get('next', '/')

    try:
        cart = request.session[settings.CART_SESSION_ID]
    except KeyError:
        cart = None
    
    try:
        order = request.session[settings.ORDER_SESSION_ID]
    except KeyError:
        order = None
    
    logout(request)

    if cart:
        request.session[settings.CART_SESSION_ID] = cart
    
    if order:
        request.session[settings.ORDER_SESSION_ID] = order
    
    return redirect(successful_url)

class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'account/password_reset_form.html'
    email_template_name = 'account/password_reset_email.html'
    success_url = reverse_lazy('account:password_reset_done')
    from_email = settings.PROJECT_EMAIL_ADDRESS

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'account/password_reset_confirm.html'
    success_url = reverse_lazy('account:password_reset_complete')

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'account/password_reset_complete.html'

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'account/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        context['first_name'] = user.first_name
        context['last_name'] = user.last_name
        context['phone_number'] = user.phone_number
        context['email'] = user.email
            
        return context

@login_required
def purchase_history(request):
    user = request.user

    orderItem_querySet = OrderItem.objects                                                             \
        .select_related('product')                                                                     \
        .only('price', 'quantity', 'order_id', 'product_id', 'product__image', 'product__name',)       \
        .order_by('-quantity')
        
    order_list = Order.objects.filter(user=user)                                                       \
        .annotate(total_cost=Sum(F('items__quantity') * F('items__price'), output_field=FloatField())) \
        .only('payment_status', 'created')                                                             \
        .prefetch_related(Prefetch('items', queryset=orderItem_querySet))                              \
        .order_by('-created')

    return render(request, 'account/profile_orders_history.html', {'order_list': order_list})
        
    
@login_required
def favorites(request):

    if request.method == 'GET':
        user = request.user
        queryset = user.favourites.only('price', 'name', 'image')

        return render(request, 'account/profile_favorite.html', {'favourite_list': queryset})
    
    elif request.method == 'POST':
        action = request.POST.get('action')
        product_id = request.POST.get('product_id')

        error_list = []
        form = forms.ValidateFavouriteProducts(request=request, data=request.POST)

        if form.is_valid():
            if action == 'add-product':
                form.add_product() 
            elif action == 'remove-product':
                form.remove_product()
        else:
            error_list = get_form_errors(form)
        
        return JsonResponse({'errors': error_list})

    else:
        return HttpResponseBadRequest()


@ajax_required
def update_user_data(request):
    error_list = []

    if request.method == 'POST':
        form = forms.UpdateUserData(data=request.POST, request=request)

        if form.is_valid():
            form.update_data()

            return JsonResponse({'status': 'ok'})
        else:
            error_list = get_form_errors(form=form)
    
    return JsonResponse({'status': 'ko', 'errors': error_list})

eshop_sample_project/templates/cart/cart.html
{% extends "base.html" %} {% load static %} {% block title %}{% endblock title %} {% block css %}
<link rel="stylesheet" href="{% static 'css/basket-style.css' %}"> {% endblock css %} {% block content %} {% if request.cart %}
<div id="main-container-basket">

    <!-- breadcrumbs -->
    <ul id="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{% url 'product_list' %}">Все товары</a></li>
        <li class="breadcrumb-item active"><a href="#">Моя корзина</a></li>
    </ul>

    <!-- caption -->
    <h5>Моя корзина<span id="quantity-of-products">({{ request.cart|length }})</span></h5>

    <div class="row">


        <div class="col-md-12 col-lg-3 order-lg-last order-md-last order-last">
            <div class="col-for-total">
                <div class="row no-gutters">

                    <!-- coupons -->
                    <!-- <div class="col-lg-12 col-md-6">
            <div class="coupon-area">
              <div class="code-group">
                <label for="code-input">Купон на скидку или подарочная карта</label>
                <div class="input-group flex-nowrap">
                  <input id="code-input" class="code-coupon" type="text" />
                  <button class="use-coupon btn">
                    ПРИМЕНИТЬ
                  </button>
                </div>
              </div>
            </div>
          </div> -->

                    <!-- total -->
                    <div class="col-lg-12 col-md-12">
                        <div class="total-area">
                            <div class="total-info">
                                <span>Итого:</span>
                                <span id="cart-total-price" class="total-cost-in-total-area">{{ cart.get_total_price|floatformat:"0" }}
                                    p.</span>
                            </div>

                            <a href="{% url 'order:new_order' %}" class="btn btn-warning">Перейти к оформлению</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-12 order-lg-first order-md-fisrt order-first">

            {% for item in cart %} {% with item.product as product %}
            <!-- product one -->
            <div id="product-line-{{ product.id }}" class="cart-item">
                <div class="row align-items-center">

                    <!-- image block -->
                    <div class="col-lg-2 col-md-2 col-4">
                        <div class="wrapper-for-img-product">
                            <a href="{% url 'product_detail' product.id product.slug %}">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}"> 
                                {% else %}
                                    <img src="{{ product.get_default_image_url }}"> 
                                {% endif %}
                            </a>
                        </div>
                    </div>

                    <!-- info block -->
                    <div class="col-lg-10 col-md-10 col-8">
                        <div class="cart-info-product">
                            <div class="row">

                                <!-- name and price -->
                                <div class="col-lg-8 col-md-8 col-12">
                                    <div class="cart-name-and-price">
                                        <div class="product-name">
                                            <a href="{{ product.get_absolute_url }}">{{ product.name|truncatechars_html:65 }}</a>
                                        </div>
                                        <div class="product-price">{{ item.total_price|floatformat:"0" }} p.</div>
                                    </div>
                                </div>

                                <!-- quantity and delete -->
                                <div class="col-lg-4 col-md-4 col-12">
                                    <div class="cart-quantity-and-delete">

                                        <!-- quantity block -->
                                        <div class="quantity-block">
                                            <button class="quantity-minus" data-product-id="{{ product.id }}">
                                                <ion-icon class="new-icon-minus" name="remove-outline"></ion-icon>
                                            </button>

                                            <input type="text" class="window-quantity" data-product-id="{{ product.id }}" data-product-price="{{ item.price|floatformat:'0' }}" value="{{ item.quantity }}" readonly />


                                            <button class="quantity-plus" data-product-id="{{ product.id }}">
                                                <ion-icon class="new-icon-plus" name="add-outline"></ion-icon>
                                            </button>
                                        </div>

                                        <!-- delete btn -->
                                        <div class="delete-block">
                                            <button class="button-delete btn" data-product-id="{{ product.id }}" data-toggle="tooltip" data-placement="right" title="Удалить из корзины">
                                                <img src="{% static 'images/delete.png' %}">
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endwith %} {% endfor %}

        </div>
    </div>
</div>
</div>
{% else %}

<div id="main-container-basket" class="container">
    <!-- breadcrumbs -->
    <ul id="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{% url 'product_list' %}">Все товары</a></li>
        <li class="breadcrumb-item active"><a href="#">Моя корзина</a></li>
    </ul>

    <div class="row">
        <div class="col-md-12">

            <div class="empty-basket-block">
                <h1 class="caption-empty-basket">В корзине пока нет товаров.</h1>

                <p class="picture-empty-basket"><i class="fas fa-shopping-basket"></i></p>
                <p class="text-empty-basket">Индивидуальный подбор товара по телефону (бесплатно по России):</p>
                <span class="tel-empty-basket">8 800 700 15 00</span>
            </div>
        </div>
    </div>
</div>
{% endif %} {% endblock content %} {% block js %}
<script src="{% static 'js/cart.js' %}"></script>
{% endblock js %}